# Generated by Django 5.0.4 on 2025-01-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='geography', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Заголовок')),
                ('table', models.TextField(default=None, verbose_name='Таблица')),
                ('graph', models.ImageField(default=None, upload_to='geography', verbose_name='График')),
            ],
        ),
    ]
