# Generated by Django 5.0.4 on 2025-01-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='graph2',
            field=models.ImageField(default=None, upload_to='geography2', verbose_name='График2'),
        ),
    ]
