# Generated by Django 5.0.4 on 2025-01-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_geography_graph2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='graph2',
            field=models.ImageField(blank=True, null=True, upload_to='geography2', verbose_name='График2'),
        ),
    ]
