# Generated by Django 5.0.4 on 2025-01-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_geography_graph2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='graph2',
            field=models.ImageField(default='path/to/default/image.png', upload_to='geography2', verbose_name='График2'),
        ),
    ]
