# Generated by Django 5.0.4 on 2025-01-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_geography_graph2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='graph2',
        ),
    ]
