# Generated by Django 5.0.4 on 2025-01-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_geography_graph2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='relevance', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Текст')),
                ('graph_left', models.ImageField(default=None, upload_to='relevance', verbose_name='График №2')),
                ('graph_right', models.ImageField(default=None, upload_to='relevance', verbose_name='График №1')),
            ],
        ),
    ]
