# Generated by Django 5.0.4 on 2025-01-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_relevance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='skills', max_length=100, verbose_name='Заголовок')),
                ('graph_2015', models.ImageField(default=None, upload_to='skills2015', verbose_name='График 2015')),
                ('graph_2016', models.ImageField(default=None, upload_to='skills2016', verbose_name='График 2016')),
                ('graph_2017', models.ImageField(default=None, upload_to='skills2017', verbose_name='График 2017')),
                ('graph_2018', models.ImageField(default=None, upload_to='skills2018', verbose_name='График 2018')),
                ('graph_2019', models.ImageField(default=None, upload_to='skills2019', verbose_name='График 2019')),
                ('graph_2020', models.ImageField(default=None, upload_to='skills2020', verbose_name='График 2020')),
                ('graph_2021', models.ImageField(default=None, upload_to='skills2021', verbose_name='График 2021')),
                ('graph_2022', models.ImageField(default=None, upload_to='skills2022', verbose_name='График 2022')),
                ('graph_2023', models.ImageField(default=None, upload_to='skills2023', verbose_name='График 2023')),
                ('graph_2024', models.ImageField(default=None, upload_to='skills2024', verbose_name='График 2024')),
                ('text', models.TextField(default=None, verbose_name='Текст')),
            ],
        ),
    ]
