# Generated by Django 5.0.4 on 2025-01-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='graph_2',
            field=models.ImageField(default=None, upload_to='geography_2', verbose_name='График 2'),
        ),
        migrations.AddField(
            model_name='relevance',
            name='table',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
    ]
