# Generated by Django 5.0.4 on 2025-01-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_geography_graph_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='table',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='skills',
            name='table10',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='skills',
            name='table2',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='skills',
            name='table3',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='skills',
            name='table4',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='skills',
            name='table5',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='skills',
            name='table6',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='skills',
            name='table7',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='skills',
            name='table8',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='skills',
            name='table9',
            field=models.TextField(default=None, verbose_name='Таблица'),
        ),
    ]
