# Generated by Django 5.0.4 on 2025-01-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_skills_table_skills_table10_skills_table2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevance',
            name='table2',
            field=models.TextField(default=None, verbose_name='Таблица2'),
        ),
    ]
