# Generated by Django 5.0.4 on 2025-01-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_relevance_table2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevance',
            name='table2',
        ),
    ]
