# Generated by Django 5.0.4 on 2025-01-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_relevance_table2'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevance',
            name='table2',
            field=models.TextField(default=None, verbose_name='Таблица2'),
        ),
    ]
