# Generated by Django 5.0.4 on 2025-01-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_relevance_table2'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='graph2',
            field=models.ImageField(default=None, upload_to='geography2', verbose_name='График2'),
        ),
        migrations.AddField(
            model_name='geography',
            name='table2',
            field=models.TextField(default=None, verbose_name='Таблица2'),
        ),
    ]
