# Generated by Django 5.0.4 on 2025-01-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_geography_graph2_geography_table2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='skills', max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('diagram', models.ImageField(default=None, upload_to='skills', verbose_name='Диаграмма')),
                ('table', models.TextField(default=None, verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.AlterModelOptions(
            name='geography',
            options={'verbose_name': 'География', 'verbose_name_plural': 'География'},
        ),
        migrations.AlterModelOptions(
            name='relevance',
            options={'verbose_name': 'Востребованность', 'verbose_name_plural': 'Востребованность'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навыки', 'verbose_name_plural': 'Навыки'},
        ),
    ]
