# Generated by Django 5.0.4 on 2025-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_skills_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='geography',
            name='graph',
            field=models.ImageField(default=None, upload_to='geography', verbose_name='Диаграмма'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='graph2',
            field=models.ImageField(default=None, upload_to='geography2', verbose_name='Диаграмма'),
        ),
        migrations.AlterField(
            model_name='relevance',
            name='graph_left',
            field=models.ImageField(default=None, upload_to='relevance', verbose_name='Диаграмма'),
        ),
        migrations.AlterField(
            model_name='relevance',
            name='graph_right',
            field=models.ImageField(default=None, upload_to='relevance', verbose_name='Диаграмма'),
        ),
    ]
